# Generated by Django 4.1.7 on 2023-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leadershiptype_image_question_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershiptype',
            name='description2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadershiptype',
            name='description3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadershiptype',
            name='description4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadershiptype',
            name='description5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leadershiptype',
            name='external_links',
            field=models.TextField(blank=True, help_text='Please enter all links comma seprated'),
        ),
        migrations.AddField(
            model_name='leadershiptype',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='leadershiptype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(choices=[('1', 'Strongly Disagree'), ('2', 'Disagree'), ('3', 'Neither Agree Nor Disagree'), ('4', 'Agree'), ('5', 'Strongly Agree')], max_length=2),
        ),
    ]
