# Generated by Django 4.1.7 on 2023-04-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_leadershiptype_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershiptype',
            name='external_links_text',
            field=models.TextField(blank=True, help_text='Please enter text for the link in same order with comma seprated'),
        ),
    ]
