# Generated by Django 4.1.7 on 2023-04-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_leadershiptype_external_links_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadershiptype',
            name='external_links',
            field=models.TextField(blank=True, help_text='<p><b style="color:orange">Note: </b>Please enter all links comma seprated.</p>'),
        ),
        migrations.AlterField(
            model_name='leadershiptype',
            name='external_links_text',
            field=models.TextField(blank=True, help_text='<p><b style="color:orange">Note: </b>Please enter diplay text for the links in same order(External links) with comma seprated.</p>'),
        ),
    ]
