# Generated by Django 4.1.7 on 2023-04-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondtoll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Category',
            new_name='category',
        ),
    ]
