# Generated by Django 4.1.7 on 2023-04-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondtoll', '0002_rename_category_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_slug',
        ),
    ]
