# Generated by Django 4.1.7 on 2023-04-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondtoll', '0004_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoption',
            name='answer_test',
            field=models.CharField(default='', max_length=500, verbose_name='Options'),
        ),
    ]
